update public.skpe_journey_items set name = 'Diagnóstico e Entendimento Estratégico' where code = 'PEM-01' and name = 'Diagnostico e Entendimento Estrategico';
update public.skpe_journey_items set name = 'Formulação Estratégica' where code = 'PEM-02' and name = 'Formulacao Estrategica';
update public.skpe_journey_items set name = 'Desdobramento Estratégico' where code = 'PEM-03' and name = 'Desdobramento Estrategico';
update public.skpe_journey_items set name = 'Implementação e Mobilização' where code = 'PEM-04' and name = 'Implementacao e Mobilizacao';
update public.skpe_journey_items set name = 'Análise de Contexto e PESTEL' where code = 'PEM-01.03' and name = 'Analise de Contexto e PESTEL';
update public.skpe_journey_items set name = 'Riscos, Lacunas e Temas Críticos' where code = 'PEM-01.06' and name = 'Riscos, Lacunas e Temas Criticos';
update public.skpe_journey_items set name = 'Abertura da Formulação Estratégica' where code = 'PEM-02.01' and name = 'Abertura da Formulacao Estrategica';
update public.skpe_journey_items set name = 'Direcionadores Estratégicos' where code = 'PEM-02.02' and name = 'Direcionadores Estrategicos';
update public.skpe_journey_items set name = 'Escolhas e Posicionamento Estratégico' where code = 'PEM-02.03' and name = 'Escolhas e Posicionamento Estrategico';
update public.skpe_journey_items set name = 'Objetivos Estratégicos' where code = 'PEM-02.04' and name = 'Objetivos Estrategicos';
update public.skpe_journey_items set name = 'Modelo Estratégico Futuro' where code = 'PEM-02.05' and name = 'Modelo Estrategico Futuro';
update public.skpe_journey_items set name = 'Mapa Estratégico' where code = 'PEM-03.01' and name = 'Mapa Estrategico';
update public.skpe_journey_items set name = 'Iniciativas e Projetos Estratégicos' where code = 'PEM-03.03' and name = 'Iniciativas e Projetos Estrategicos';
update public.skpe_journey_items set name = 'Responsabilidades e Governança da Execução' where code = 'PEM-03.04' and name = 'Responsabilidades e Governanca da Execucao';
update public.skpe_journey_items set name = 'Plano de Implementação' where code = 'PEM-04.01' and name = 'Plano de Implementacao';
update public.skpe_journey_items set name = 'Comunicação e Mobilização' where code = 'PEM-04.02' and name = 'Comunicacao e Mobilizacao';
update public.skpe_journey_items set name = 'Capacidades e Gestão da Mudança' where code = 'PEM-04.03' and name = 'Capacidades e Gestao da Mudanca';
update public.skpe_journey_items set name = 'Gestão de Riscos da Implementação' where code = 'PEM-04.04' and name = 'Gestao de Riscos da Implementacao';
update public.skpe_journey_items set name = 'Análise Crítica de Desempenho' where code = 'PEM-05.02' and name = 'Analise Critica de Desempenho';
update public.skpe_journey_items set name = 'Atualização Estratégica' where code = 'PEM-05.04' and name = 'Atualizacao Estrategica';
